/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Hello } from "./Hello";
import { HelloCountArgs } from "./HelloCountArgs";
import { HelloFindManyArgs } from "./HelloFindManyArgs";
import { HelloFindUniqueArgs } from "./HelloFindUniqueArgs";
import { DeleteHelloArgs } from "./DeleteHelloArgs";
import { HelloService } from "../hello.service";
@graphql.Resolver(() => Hello)
export class HelloResolverBase {
  constructor(protected readonly service: HelloService) {}

  async _hellosMeta(
    @graphql.Args() args: HelloCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Hello])
  async hellos(@graphql.Args() args: HelloFindManyArgs): Promise<Hello[]> {
    return this.service.hellos(args);
  }

  @graphql.Query(() => Hello, { nullable: true })
  async hello(
    @graphql.Args() args: HelloFindUniqueArgs
  ): Promise<Hello | null> {
    const result = await this.service.hello(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Hello)
  async deleteHello(
    @graphql.Args() args: DeleteHelloArgs
  ): Promise<Hello | null> {
    try {
      return await this.service.deleteHello(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
