/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { LikesService } from "../likes.service";
import { LikesCreateInput } from "./LikesCreateInput";
import { Likes } from "./Likes";
import { LikesFindManyArgs } from "./LikesFindManyArgs";
import { LikesWhereUniqueInput } from "./LikesWhereUniqueInput";
import { LikesUpdateInput } from "./LikesUpdateInput";

export class LikesControllerBase {
  constructor(protected readonly service: LikesService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Likes })
  async createLikes(@common.Body() data: LikesCreateInput): Promise<Likes> {
    return await this.service.createLikes({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        likedAt: true,
        userId: true,
        postId: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Likes] })
  @ApiNestedQuery(LikesFindManyArgs)
  async likesItems(@common.Req() request: Request): Promise<Likes[]> {
    const args = plainToClass(LikesFindManyArgs, request.query);
    return this.service.likesItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        likedAt: true,
        userId: true,
        postId: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Likes })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async likes(
    @common.Param() params: LikesWhereUniqueInput
  ): Promise<Likes | null> {
    const result = await this.service.likes({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        likedAt: true,
        userId: true,
        postId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Likes })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateLikes(
    @common.Param() params: LikesWhereUniqueInput,
    @common.Body() data: LikesUpdateInput
  ): Promise<Likes | null> {
    try {
      return await this.service.updateLikes({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          likedAt: true,
          userId: true,
          postId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Likes })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteLikes(
    @common.Param() params: LikesWhereUniqueInput
  ): Promise<Likes | null> {
    try {
      return await this.service.deleteLikes({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          likedAt: true,
          userId: true,
          postId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
